#ifndef __BUTTONSSEMAFORO_H__
#define  __BUTTONSSEMAFORO_H__ 

#define BUTTON_SCREEN_BACK 0
#define BUTTON_SCREEN_XD 1
#define BUTTON_COUNT_SEMAFORO (BUTTON_SCREEN_BACK+1)


#endif //__BUTTONSSEMAFORO_H__ 